
services:
  # Servidor Web com PHP 7.4
  app:
    #image: php:7.4-apache
    #container_name: app 
    build:      
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8089:80"    
  
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`fbjuazeiro.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=le"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      # Middleware de segurança
      #- "traefik.http.routers.app.middlewares=security-headers"
      # Health check
      #- "traefik.http.services.app.loadbalancer.healthcheck.path=/"
      #- "traefik.http.services.app.loadbalancer.healthcheck.interval=30s"
           
    networks:
      - estacionamento
   

  # Banco de dados MySQL
  mysql:
    image: mysql:5.7
    #container_name: codeigniter_mysql
    restart: always
    #ports:
    #  - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estacionamento_mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    networks:
      - estacionamento

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    #container_name: codeigniter_phpmyadmin
    restart: always
    #ports:
    #  - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: root
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 128M
    depends_on:
      - mysql
    labels:
            - "traefik.enable=true"
            - "traefik.http.routers.phpmyadmin.rule=Host(`fbjuazeiromyadmin.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
            - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
            - "traefik.http.routers.phpmyadmin.tls=true"
            - "traefik.http.routers.phpmyadmin.tls.certresolver=le"
            - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
        
    networks:
      - estacionamento

networks:
  estacionamento:   
    external: true

volumes:
  mysql_data:
    driver: local
   