

services:
  mysql:
    image: biarms/mysql:5.7-beta-circleci   
    container_name: "mysql"
    volumes:
      - .db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      #MYSQL_DATABASE: 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - jbjuaz

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "phpmyadmin"
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    restart: always
    networks:
      - jbjuaz
    labels:
      traefik.enable: "true"
      traefik.http.routers.phpmyadmin.rule: "Host(`phpmyadmin.stesistemas.com`)"
      traefik.http.routers.phpmyadmin.entrypoints: "websecure"
      traefik.http.routers.phpmyadmin.tls.certresolver: "myresolver"
      traefik.http.services.phpmyadmin.loadbalancer.server.port: "8082"

  node:
    build:
      context: ./src     
    volumes:
      - ./src:/usr/src/app
      - ./certs:/usr/src/app/certs
    ports:
      - '3000:3000'
    #- '443:443'
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    networks:
    - jbjuaz

  labels:
    traefik.enable: "true"
    traefik.http.routers.node.rule: "Host(`fbjuazeiro.stesistemas.com`)"
    traefik.http.routers.node.entrypoints: "websecure"
    traefik.http.routers.node.tls.certresolver: "myresolver"
    traefik.http.services.node.loadbalancer.server.port: "3000"

#volumes:
#  db_data:

networks:
  jbjuaz:
    external: true

