

services:
  mysql:
    image: biarms/mysql:5.7-beta-circleci   
    #container_name: "mysql"
    volumes:
      - .db_data_jbjuaz:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      #MYSQL_DATABASE: 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    #container_name: "phpmyadmin"
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    restart: always 
    labels:
      - "traefik.enable=true"
      # Router HTTPS
      - "traefik.http.routers.paineldb-secure.rule=Host(`paineldb.stesistemas.com`) || Host(`www.paineldb.stesistemas.com`)" # Troque pelo seu Dominio
      - "traefik.http.routers.paineldb-secure.entrypoints=websecure"
      - "traefik.http.routers.paineldb-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.paineldb-secure.tls=true"
      - "traefik.http.services.paineldb.loadbalancer.server.port=8082"

      # Router HTTP com redirecionamento para HTTPS
      - "traefik.http.routers.paineldb.rule=Host(`paineldb.stesistemas.com`) || Host(`www.paineldb.stesistemas.com`)" # Troque pelo seu Dominio
      - "traefik.http.routers.paineldb.entrypoints=web"
      - "traefik.http.routers.paineldb.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.paineldb.loadbalancer.server.port=8082"

  node:
    depends_on:
      - mysql
    build: ./app 
    restart: always
    env_file: ./.env  
    #volumes:
    #  - ./app:/app
    #- ./certs:/app/certs
    ports:
      - '3000:3000'
    #- '443:443'
    links:
      - mysql
    #command: bash -c /app/start.sh  
    stdin_open: true
    tty: true  
    labels:
      - "traefik.enable=true"      
      # Router HTTPS
      - "traefik.http.routers.fbjuaz-secure.rule=Host(`fbjuaz.stesistemas.com`) || Host(`www.fbjuaz.stesistemas.com`)" # Troque pelo seu Dominio
      - "traefik.http.routers.fbjuaz-secure.entrypoints=websecure"
      - "traefik.http.routers.fbjuaz-secure.tls.certresolver=leresolver"
      - "traefik.http.routers.fbjuaz-secure.tls=true"
      - "traefik.http.services.fbjuaz.loadbalancer.server.port=3000"

      # Router HTTP com redirecionamento para HTTPS
      - "traefik.http.routers.fbjuaz.rule=Host(`fbjuaz.stesistemas.com`) || Host(`www.fbjuaz.stesistemas.com`)" # Troque pelo seu Dominio
      - "traefik.http.routers.fbjuaz.entrypoints=web"
      - "traefik.http.routers.fbjuaz.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.fbjuaz.loadbalancer.server.port=3000"  

networks:
  jbjuaz:
    external: true

#volumes:
#  db_data:

