

services:
  mysql:
    image: biarms/mysql:5.7-beta-circleci 
    volumes:
      - db_data_jbjuaz:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: estacionamentojn
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest 
    depends_on:
      - mysql
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    restart: always 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paineldb.rule=Host(`paineldb.stesistemas.com`) || Host(`www.paineldb.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.paineldb.entrypoints=websecure"
      - "traefik.http.routers.paineldb.tls.certresolver=leresolver"
      - "traefik.http.services.paineldb.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.paineldb-secure.rule=Host(`paineldb.stesistemas.com`) || Host(`www.paineldb.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.paineldb-secure.entrypoints=web"
      - "traefik.http.routers.paineldb-secure.middlewares=redirect-to-https"

  node:
    depends_on:
      - mysql
    build: ./app 
    restart: always
    env_file: ./.env  
    volumes:
      - volime_jbjuaz:/app    
    ports:
      - '5558:3000'  
    stdin_open: true
    tty: true  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fbjuaz.rule=Host(`fbjuaz.stesistemas.com`) || Host(`www.fbjuaz.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.fbjuaz.entrypoints=websecure"
      - "traefik.http.routers.fbjuaz.tls.certresolver=leresolver"
      - "traefik.http.services.fbjuaz.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.fbjuaz-secure.rule=Host(`fbjuaz.stesistemas.com`) || Host(`www.fbjuaz.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.fbjuaz-secure.entrypoints=web"
      - "traefik.http.routers.fbjuaz-secure.middlewares=redirect-to-https"     

networks:
  default:
    name: jbjuaz
    external: true

volumes:
  db_data_jbjuaz:
  volime_jbjuaz:

