version: '3.8'

services:

  mysql:
    image: biarms/mysql:5.7-beta-circleci
    #image: mysql:5.7.26
    container_name: "mysql"
    volumes:
      - .docker/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
  #    networks:
  #      - mynetwork

  phpmyadmin:
    #image: phpmyadmin/phpmyadmin
    image: phpmyadmin:latest
    container_name: "phpmyadmin"
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    restart: always
  #    networks:
  #      - mynetwork

  node:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
      - ./certs:/app/certs
    ports:
      #- '3000:3000'
      - '443:443'
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

  #nginx:
  #  image: nginx:alpine
  #  volumes:
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #    - ./certs:/etc/nginx/ssl
  #  ports:
  #    - '8001:8001'
  #    - '443:443'
  #  depends_on:
  #    - node
  #    - mysql
