

services:
  mysql:
    image: biarms/mysql:5.7-beta-circleci   
    #container_name: "mysql"
    volumes:
      - .db_data_jbjuaz:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      #MYSQL_DATABASE: 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    #container_name: "phpmyadmin"
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    restart: always 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`phpmyadmin.stesistemas.com`) || Host(`www.phpmyadmin.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=leresolver"
      - "traefik.http.services.wordpress.loadbalancer.server.port=8082"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress-secure.rule=Host(`phpmyadmin.stesistemas.com`) || Host(`www.phpmyadmin.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.wordpress-secure.entrypoints=web"
      - "traefik.http.routers.wordpress-secure.middlewares=redirect-to-https"

  node:
    depends_on:
      - mysql
    build: ./app 
    restart: always
    env_file: ./.env  
    #volumes:
    #  - ./app:/app
    #- ./certs:/app/certs
    ports:
      - '3000:3000'
    #- '443:443'
    links:
      - mysql
    #command: bash -c /app/start.sh  
    stdin_open: true
    tty: true  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`fbjuazeiro.stesistemas.com`) || Host(`www.fbjuazeiro.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=leresolver"
      - "traefik.http.services.wordpress.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress-secure.rule=Host(`fbjuazeiro.stesistemas.com`) || Host(`www.fbjuazeiro.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.wordpress-secure.entrypoints=web"
      - "traefik.http.routers.wordpress-secure.middlewares=redirect-to-https"    

networks:
  jbjuaz:
    external: true

#volumes:
#  db_data:

