

services:
  mysql:
    image: biarms/mysql:5.7-beta-circleci   
    #container_name: "mysql"
    volumes:
      - db_data_jbjuaz:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: estacionamentojn
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    #container_name: "phpmyadmin"
    depends_on:
      - mysql
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    restart: always 
    labels:       
      - "traefik.enable=true"      
      - "traefik.http.routers.phpmyadmin.rule=Host(`paineldb.stesistemas.com`) || Host(`www.paineldb.stesistemas.com`)" # Troque pelo seu Dominio
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=3000"
      - "traefik.http.routers.phpmyadmin.service=phpmyadmin"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=leresolver"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"

  node:
    depends_on:
      - mysql
    build: ./app 
    restart: always
    env_file: ./.env  
    #volumes:
    #  - ./app:/app
    #- ./certs:/app/certs
    ports:
      - '3000:3000'
    #- '443:443'
    links:
      - mysql
    #command: bash -c /app/start.sh  
    stdin_open: true
    tty: true  
    labels:
      - "traefik.enable=true"      
      - "traefik.http.routers.fbjuaz.rule=Host(`fbjuaz.stesistemas.com`) || Host(`www.fbjuaz.stesistemas.com`)" # Troque pelo seu Dominio
      - "traefik.http.services.fbjuaz.loadbalancer.server.port=3000"
      - "traefik.http.routers.fbjuaz.service=fbjuaz"
      - "traefik.http.routers.fbjuaz.tls.certresolver=leresolver"
      - "traefik.http.routers.fbjuaz.entrypoints=websecure"
      - "traefik.http.routers.fbjuaz.tls=true"     

networks:
  default:
    name: jbjuaz
    external: true

volumes:
  db_data_jbjuaz:

