

services:
  mysql:
    image: biarms/mysql:5.7-beta-circleci 
    volumes:
      - volume_db_data_jbjuaz:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: estacionamentojn
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest 
    depends_on:
      - mysql
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    restart: always 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paineldb.rule=Host(`paineldb.stesistemas.com`) || Host(`www.paineldb.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.paineldb.entrypoints=websecure"
      - "traefik.http.routers.paineldb.tls.certresolver=leresolver"
      - "traefik.http.services.paineldb.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.paineldb-secure.rule=Host(`paineldb.stesistemas.com`) || Host(`www.paineldb.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
      - "traefik.http.routers.paineldb-secure.entrypoints=web"
      - "traefik.http.routers.paineldb-secure.middlewares=redirect-to-https"

  
  wsnode:
    depends_on:
      - mysql
    build: ./websockt 
    restart: always
    env_file: ./.env  
    volumes:
      - volume_wsjbjuaz:/app 
      - volume_wsjbjuaz_fotos:/app/public/uploads/car    
    ports:
      - '9090:3001'  
    stdin_open: true
    tty: true  
    labels:
      # Rota HTTP para redirecionar para HTTPS
      - "traefik.http.routers.wsnode-http.rule=Host(`wsjuazeiro.stesistemas.com`)"
      - "traefik.http.routers.wsnode-http.service=wsnode-http"
      - "traefik.http.routers.wsnode-http.entrypoints=web"
      - "traefik.http.routers.wsnode-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # Rota HTTPS normal
      - "traefik.enable=true"
      - "traefik.http.routers.wsnode-https.rule=Host(`wsjuazeiro.stesistemas.com`)" #Coloque o Seu Dominio do wsnode Aqui
      - "traefik.http.routers.wsnode-https.service=wsnode-https"
      - "traefik.http.routers.wsnode-https.entrypoints=websecure"
      - "traefik.http.routers.wsnode-https.tls=true"
      - "traefik.http.routers.wsnode-https.tls.certresolver=leresolver" 
      - "traefik.http.services.wsnode-https.loadbalancer.server.port=3001" 

  node:
    depends_on:
      - mysql
      - wsnode
    build: ./app 
    restart: always
    env_file: ./.env  
    volumes:
      - volume_jbjuaz:/app
      - volume_wsjbjuaz_fotos:/app/public/uploads/car     
    ports:
      - '3000:3000'  
    stdin_open: true
    tty: true  
    labels:
      # Rota HTTP para redirecionar para HTTPS
      - "traefik.http.routers.node-http.rule=Host(`fbjuaz.stesistemas.com`)"
      - "traefik.http.routers.node-http.service=node-http"
      - "traefik.http.routers.node-http.entrypoints=web"
      - "traefik.http.routers.node-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # Rota HTTPS normal
      - "traefik.enable=true"
      - "traefik.http.routers.node-https.rule=Host(`fbjuaz.stesistemas.com`)" #Coloque o Seu Dominio do node Aqui
      - "traefik.http.routers.node-https.service=node-https"
      - "traefik.http.routers.node-https.entrypoints=websecure"
      - "traefik.http.routers.node-https.tls=true"
      - "traefik.http.routers.node-https.tls.certresolver=leresolver" 
      - "traefik.http.services.node-https.loadbalancer.server.port=3000" 
  
    
networks:
  default:
    name: jbjuaz
    external: true

volumes:
  volume_db_data_jbjuaz:
  volume_wsjbjuaz:
  volume_wsjbjuaz_fotos:
  volume_jbjuaz:

