
services:
    nginx:
        #image: nginx:alpine
        container_name: nginx
        build:
            context: ./etc/nginx
            dockerfile: Dockerfile
        volumes:
            #- "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "../:/var/www/html"
            #- "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "${NGINX_PORT}:80"
            #- 9098:80
        env_file:
            - ".env"
        restart: always
        depends_on:
            - php-fpm
            - mysql
        labels:
            - "traefik.enable=true"
            #- "traefik.http.routers.nginx.rule=Host(`fbjuazeiro.stesistemas.com`) || Host(`www.fbjuazeiro.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
            - "traefik.http.routers.nginx.rule=Host(`fbjuazeiro.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
            - "traefik.http.routers.nginx.entrypoints=websecure"
            - "traefik.http.routers.nginx.tls.certresolver=le"
            - "traefik.http.services.nginx.loadbalancer.server.port=80"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            #- "traefik.http.routers.nginx-secure.rule=Host(`fbjuazeiro.stesistemas.com`) || Host(`www.fbjuazeiro.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
            - "traefik.http.routers.nginx-secure.rule=Host(`fbjuazeiro.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
            - "traefik.http.routers.nginx-secure.entrypoints=web"
            - "traefik.http.routers.nginx-secure.middlewares=redirect-to-https"
       
    php-fpm:
        container_name: php-fpm
        build:
            context: ./etc/php
            dockerfile: Dockerfile
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../:/var/www/html"
       

    #composer:
    #    container_name: composer
    #    build:
    #        context: ./etc/composer
    #        dockerfile: Dockerfile
    #    volumes:
    #        - "../:/app"
    #    command: install
  

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "${PHP_MY_ADMIN_PORT}:80"
            #- 9099:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_MAPOS_HOST}
            - PMA_USER=${MYSQL_MAPOS_USER}
            - PMA_PASSWORD=${MYSQL_MAPOS_PASSWORD}
        restart: always
        depends_on:
            - mysql
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.phpmyadmin.rule=Host(`fbjuazeiromyadmin.stesistemas.com`) || Host(`www.fbjuazeiromyadmin.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
            - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
            - "traefik.http.routers.phpmyadmin.tls.certresolver=le"
            - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.routers.phpmyadmin-secure.rule=Host(`fbjuazeiromyadmin.stesistemas.com`) || Host(`www.fbjuazeiromyadmin.stesistemas.com`)" # Troque pelo seu dominio ou subdominio
            - "traefik.http.routers.phpmyadmin-secure.entrypoints=web"
            - "traefik.http.routers.phpmyadmin-secure.middlewares=redirect-to-https"
        

    mysql:
        image: mysql:${MYSQL_MAPOS_VERSION}
        container_name: mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_MAPOS_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_MAPOS_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_MAPOS_USER}
            - MYSQL_PASSWORD=${MYSQL_MAPOS_PASSWORD}
        ports:
            - "${MYSQL_MAPOS_PORT}:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
       

networks:
  default:
    name: estacionamento
    external: true
    
    
